"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { apiFetch } from "@/lib/api/client";
import { format } from "date-fns";

interface SharedEncounter {
  patient_name: string;
  start_time?: string;
  summary?: {
    chief_complaint?: string;
    assessment?: string;
    plan?: string;
    diagnosis: string[];
  };
  medications: Array<{ name: string; dosage: string; frequency: string; duration: string }>;
}

export default function SharedEncounterPage() {
  const { token } = useParams<{ token: string }>();
  const [data, setData] = useState<SharedEncounter | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    apiFetch<SharedEncounter>(`/encounters/shared/${token}`)
      .then(setData)
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false));
  }, [token]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="w-6 h-6 border-2 border-black border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="text-center text-gray-500">
          <p className="text-lg font-medium mb-2">Encounter not found</p>
          <p className="text-sm">This link may have expired or is invalid.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8 px-4">
      <div className="max-w-2xl mx-auto">
        <div className="bg-white border border-gray-200 rounded-xl overflow-hidden">
          {/* Header */}
          <div className="bg-black text-white px-6 py-4">
            <p className="text-xs uppercase tracking-widest opacity-60 mb-1">ScribeDesk — Shared Encounter</p>
            <h1 className="text-xl font-semibold">{data.patient_name}</h1>
            {data.start_time && (
              <p className="text-sm opacity-70 mt-0.5">{format(new Date(data.start_time), "MMMM d, yyyy · h:mm a")}</p>
            )}
          </div>

          <div className="p-6 space-y-6">
            {data.summary && (
              <>
                {data.summary.chief_complaint && (
                  <section>
                    <h2 className="text-xs font-semibold text-gray-400 uppercase tracking-widest mb-2">Chief Complaint</h2>
                    <p className="text-sm text-gray-800">{data.summary.chief_complaint}</p>
                  </section>
                )}
                {data.summary.assessment && (
                  <section>
                    <h2 className="text-xs font-semibold text-gray-400 uppercase tracking-widest mb-2">Assessment</h2>
                    <p className="text-sm text-gray-800">{data.summary.assessment}</p>
                  </section>
                )}
                {data.summary.plan && (
                  <section>
                    <h2 className="text-xs font-semibold text-gray-400 uppercase tracking-widest mb-2">Plan</h2>
                    <p className="text-sm text-gray-800">{data.summary.plan}</p>
                  </section>
                )}
                {data.summary.diagnosis && data.summary.diagnosis.length > 0 && (
                  <section>
                    <h2 className="text-xs font-semibold text-gray-400 uppercase tracking-widest mb-2">Diagnoses</h2>
                    <div className="flex flex-wrap gap-1.5">
                      {data.summary.diagnosis.map((d, i) => (
                        <span key={i} className="px-2 py-0.5 border border-gray-300 rounded text-xs text-gray-700">{d}</span>
                      ))}
                    </div>
                  </section>
                )}
              </>
            )}

            {data.medications.length > 0 && (
              <section>
                <h2 className="text-xs font-semibold text-gray-400 uppercase tracking-widest mb-2">Medications</h2>
                <div className="space-y-2">
                  {data.medications.map((m, i) => (
                    <div key={i} className="flex items-start gap-3 px-3 py-2 border border-gray-200 rounded-lg">
                      <div>
                        <p className="text-sm font-medium text-gray-900">{m.name} {m.dosage}</p>
                        <p className="text-xs text-gray-500">{m.frequency} · {m.duration}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </section>
            )}

            <p className="text-[10px] text-gray-300 text-center pt-2">
              Read-only view · Generated by ScribeDesk AI · Reviewed by attending physician
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
